import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { TwentyFirstToolbar } from "@21st-extension/toolbar-next";
import ColorBends from "./utils/ColorBends";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const silverGarden = localFont({
  src: "../public/asset/fonts/Silver-Garden-Font/Silver Garden.otf",
  variable: "--font-silver-garden",
});

const kollektif = localFont({
  src: "../public/asset/fonts/kollektif/Kollektif.ttf",
  variable: "--font-kollektif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${silverGarden.variable} ${kollektif.variable} antialiased`}
      >
        <ColorBends
          className="absolute top-0 left-0 w-full h-full"
          colors={['#FF0000', '#00FF00', '#0000FF']}
        />
        <TwentyFirstToolbar
          config={{
            plugins: [], // Add your custom plugins here
          }}
        />
        {children}
      </body>
    </html>
  );
}
